Repository we-dance/platform, pull requests merged in 2022-02, with the labels that each got.

#89 feat: event: edit list of profiles
  components/TButton.vue
  components/TCommentsInline.vue
  components/TDropdown.vue
  components/TDropdownSeparator.vue
  components/TInput/TInputArray.vue
  components/TInput/TInputProfile.vue
  components/TItemCreator.vue
  components/TProfile.vue
  components/TProfileContacts.vue
  components/global/WProfile.vue
  layouts/default.vue
  locales/en.yml
  pages/demo/team.vue
  pages/events/_id/edit.vue
  pages/events/_id/index.vue
  use/events.js
  use/posts.js
Labels: enhancement

#114 i18n: Settings
  locales/en.yml
  pages/settings.vue
  use/accounts.js
  use/common.js
  use/profiles.js
Labels: i18n

#111 i18n: Auth
  components/Actions/TReactions.vue
  components/Actions/TStars.vue
  components/TButton.vue
  components/TPost.vue
  layouts/default.vue
  locales/en.yml
Labels: i18n

#135 i18n: post editor #77
  locales/en.yml
  pages/events/_id/edit.vue
  pages/posts/_id/edit.vue
  use/posts.js
Labels: i18n

#146 i18n: Event Dashboard
  locales/en.yml
  pages/events/_id/dashboard.vue
Labels: i18n

#147 i18n: auth
  components/Actions/TReactions.vue
  components/Actions/TStars.vue
  components/TButton.vue
  locales/en.yml
Labels: i18n

#148 api: search by instagram and facebook
  functions/src/index.ts
  functions/src/lib/algolia.ts
Labels: firebase-function

#153 i18n: profile #74
  components/TCardActions.vue
  components/TItemToolbar.vue
  components/TPost.vue
  components/TPostList.vue
  components/TProfile.vue
  components/TProfileDetails.vue
  locales/en.yml
Labels: i18n

#155 fix(Event Editor): import profile
  components/TInput/TInputArray.vue
Labels: enhancement

#161 chore: debug i18n
  locales/en.yml
  nuxt.config.js
Labels: chore

#160 fix: lint errors
  .eslintrc.js
  components/Actions/TReaction.vue
  components/Actions/TReactions.vue
  components/Actions/TStars.vue
  components/Card/TCardEvent.vue
  components/Card/TCardLink.vue
  components/Card/TCardPoll.vue
  components/TButton.vue
  components/TCommentsInline.vue
  components/TDropdownSelect.vue
  components/TForm.vue
  components/TInput/TInputArray.vue
  components/TInput/TInputButtons.vue
  components/TInput/TInputProfile.vue
  components/TInput/TInputSelectSmall.vue
  components/TPost.vue
  components/TPostList.vue
  components/TStyles.vue
  components/global/WList.vue
  components/global/WProfile.vue
  components/global/WTeaser.vue
  package.json
  pages/demo/date.vue
  pages/demo/team.vue
  pages/feed.vue
  pages/posts/_id/edit.vue
  pages/register.vue
  plugins/firebase.js
  use/events.js
  use/posts.js
  utils.js
Labels: bug, chore

#156 i18n: Event Editor #75
  components/MainNavigation.vue
  components/TForm.vue
  components/TInput/TInputPhoto.vue
  locales/en.yml
  pages/events/_id/edit.vue
  use/common.js
  use/events.js
  use/profiles.js
Labels: i18n

#164 chore: add tailwind typography plugin #127
  components/TPreview.vue
  components/TProfile.vue
  package.json
  pages/_slug/index.vue
  pages/dance/_slug.vue
  pages/dance/index.vue
  pages/nopassword.vue
  tailwind.config.js
  yarn.lock
Labels: chore
