Repository we-dance/platform, pull requests merged in 2022-01, with the labels that each got.

#90 i18n: feed #79
  components/TItemComments.vue
  components/TItemToolbar.vue
  locales/en.yml
  pages/feed.vue
  use/posts.js
Labels: i18n

#84 i18n: Calendar
  locales/de.yml
  locales/en.yml
  locales/es.yml
  locales/fr.yml
  locales/he.yml
  locales/it.yml
  locales/pl.yml
  locales/pt.yml
  locales/ro.yml
  locales/ru.yml
  locales/sr.yml
  locales/tr.yml
  pages/events/index.vue
Labels: i18n

#93 chore: i18n form fields
  components/Card/TCardEvent.vue
  components/TEventText.vue
  components/TInput/TInputVenue.vue
  pages/community.vue
  pages/events/_id/dashboard.vue
  pages/events/_id/edit.vue
  pages/events/_id/index.vue
  pages/events/index.vue
  pages/feed.vue
  pages/posts/_id/edit.vue
  pages/register.vue
  pages/settings.vue
  use/accounts.js
  use/events.js
  use/forms.js
  use/i18n.js
  use/posts.js
  use/profiles.js
  use/venues.js
Labels: i18n

#85 style: i18n
  components/MainNavigation.vue
  layouts/popup.vue
  locales/de.yml
  locales/en.yml
  locales/es.yml
  locales/fr.yml
  locales/he.yml
  locales/it.yml
  locales/pl.yml
  locales/pt.yml
  locales/ro.yml
  locales/ru.yml
  locales/sr.yml
  locales/tr.yml
  pages/index.vue
  pages/settings.vue
Labels: i18n

#105 i18n: Chat
  locales/en.yml
  pages/chat/_slug.vue
  pages/chat/index.vue
Labels: i18n

#104 i18n: Calendar
  locales/en.yml
  pages/events/index.vue
  use/events.js
Labels: i18n

#108 i18n: Event view
  locales/en.yml
  pages/events/_id/index.vue
Labels: i18n

#116 fix calendar type filter
  components/TEventText.vue
  pages/events/index.vue
Labels: bug

#112 i18n: Home
  locales/en.yml
  pages/index.vue
Labels: i18n

#119 refactor: TField use component instead of type
  components/TAccountSelector.vue
  components/TCardActions.vue
  components/TField.vue
  components/TForm.vue
  components/TGridParticipants.vue
  components/TInput/TInputTags.vue
  components/TInput/TInputVenue.vue
  components/TInput/TInputZipcode.vue
  components/TListComments.vue
  pages/admin/cities.vue
  pages/admin/emails.vue
  pages/admin/reports.vue
  pages/admin/templates.vue
  pages/demo/city.vue
  pages/demo/date.vue
  pages/events/_id/dashboard.vue
  pages/onboarding.vue
  pages/settings.vue
  plugins/vue-tailwind.js
  use/accounts.js
  use/events.js
  use/posts.js
  use/profiles.js
  use/venues.js
Labels: enhancement

#121 chore: cleanup firebase libraries
  components/TButtonShare.vue
  components/TFormComment.vue
  components/TInput/TInputCity.vue
  components/TInput/TInputCollection.vue
  components/TInput/TInputLocation.vue
  components/TInput/TInputLocationSelect.vue
  components/TItemEdit.vue
  components/TProfileContact.vue
  jest.config.js
  layouts/default.vue
  nuxt.config.js
  package.json
  pages/events/_id/edit.vue
  pages/nopassword.vue
  pages/posts/_id/edit.vue
  pages/register.vue
  pages/settings.vue
  pages/signin.vue
  plugins/firebase.js
  use/app.js
  use/filters.js
  use/google-loader.js
  yarn.lock
Labels: chore

#122 speedup page loading
  components/Card/TCardEvent.vue
  components/TAvatar.vue
  components/TButton.vue
  components/TEventText.vue
  components/TFooter.vue
  components/TPost.vue
  components/TProfile.vue
  components/TProfileCard3.vue
  components/TStyles.vue
  components/global/WProfile.vue
  layouts/public.vue
  pages/chat/_slug.vue
  pages/chat/index.vue
  pages/community.vue
  pages/dance/_slug.vue
  pages/dance/index.vue
  pages/events/index.vue
  pages/index.vue
  pages/lists/index.vue
  pages/nopassword.vue
  pages/register.vue
  pages/search.vue
  pages/settings.vue
  pages/signin.vue
Labels: enhancement

#126 feat(Event): description and comments
  components/TCardComment.vue
  components/TCardList.vue
  components/TCommentsInline.vue
  components/TFormComment.vue
  components/TItemComments.vue
  components/TListComments.vue
  components/TPost.vue
  components/TPostList.vue
  pages/_slug/edit.vue
  pages/_slug/index.vue
  pages/_slug/share.vue
  pages/events/_id/index.vue
  pages/events/_id/share.vue
  pages/posts/_id/index.vue
  pages/posts/_id/share.vue
  use/app.js
  utils.js
Labels: enhancement

#133 feat: show version in footer
  components/TFooter.vue
  package.json
Labels: enhancement
